<?php

namespace Database\Seeders;

use App\Models\CompanyObject;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CompanyObjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $objects = [
            'UNRESTRICTED',
            'ACCOUNTANCY',
            'ADVERTISING',
            'ADVERTISING PROMOTION',
            'AGRICULTURAL MACHINERY',
            'AIR CONDITIONING',
            'AIR TRANSPORT',
            'ALARMS',
            'ALTERNATE MEDICINE',
            'ANTIQUES',
            'ARCHITECTS',
            'ARCHITECTS WITH CLAUSE',
            'ART GALLERIES',
            'BAKERY',
            'BALLOONS',
            'BICYCLES',
            'BLINDS',       
            'BOOKS',
            'BOOK KEEPING',
            'BOOTS & SHOES',
            'BATHROOMS',

            // 'CABINET MAKERS',
            // 'CAFES',
            // 'CAMPING EQUIPMENT',
            // 'CAR DEALERS',
            // 'CAR HIRE',
            // 'CAR PARKS',
            // 'CAR REPAIRS',
            // 'CAR VALETING',
            // 'CARAVAN PARKS',
            // 'CARAVANS',
            // 'CARPENTRY',
            // 'CARPET CLEANING',
            // 'CARPETS',
            // 'CARTONS',
            // 'CATERING',
            // 'CEILINGS',
            // 'CENTRAL HEATING',
            // 'CERAMICS',
            // 'CHARITY',
            // 'CHARTERED SURVEYORS',
            // 'CHAUFFEUR SERVICES',
            // 'CHEMICALS',
            // 'CHILDCARE',
            // 'CHIMNEY SWEEPS',
            // 'CHINA',
            // 'CHIROPODISTS',
            // 'CHIROPRACTORS',
            // 'CHURCH',
            // 'CINEMAS',
            // 'CIVIL ENGINEERS',
            // 'CLEANING',
            // 'CLEANING MATERIALS',
            // 'CLOTHING',
            // 'CLUBS',
            // 'COACHES',
            // 'COFFEE SHOPS',
            // 'COMMODITY BROKERS',
            // 'COMMUNICATIONS',
            // 'COMPUTER CONSULTANTS',
            // 'COMPUTER EQUIPMENT',
            // 'COMPUTER PROGRAMMING',
            // 'COMPUTER SERVICES',
            // 'COMPUTER SOFTWARE',
            // 'CONFECTIONERY',
            // 'CONFERENCE SERVICES',
            // 'CONSTRUCTION',
            // 'CONSULTANTS',
            // 'CONVENIENCE STORES',
            // 'COURIERS',
            // 'CRAFTS',
            // 'CURTAINS',
            // 'DAIRY FARMING',
            // 'DANCE SCHOOLS',
            // 'DATA PROCESSING',
            // 'DEBT COLLECTORS',
            // 'DECORATING',
            // 'DECORATORS',
            // 'DELICATESSENS',
            // 'DEMOLITION',
            // 'DENTISTS',
            // 'DEPARTMENT STORES',
            // 'DESIGN',
            // 'DESIGN CONSULTANTS',
            // 'DISABILITY BEDS',
            // 'DIESEL ENGINEERS',
            // 'DIRECT MAIL',
            // 'DISCOTHEQUES',
            // 'DIY STORES',
            // 'DOCTORS',
            // 'DOMESTIC APPLIANCES',
            // 'DOUBLE GLAZING',
            // 'DRAINAGE',
            // 'DRIVING SCHOOLS',
            // 'DRY CLEANERS',
            // 'DYERS',
            // 'EDUCATION',
            // 'ELECTRICAL APPLIANCES',
            // 'ELECTRICAL CONTRACTORS',
            // 'ELECTRICAL ENGINEERS',
            // 'ELECTRICAL GOODS',
            // 'ELECTRONIC EQUIPMENT',
            // 'EMPLOYMENT AGENTS',
            // 'ENGINEERING',
            // 'ENGINEERS',
            // 'ENGRAVERS',
            // 'ENTERTAINMENT',
            // 'ENVIRONMENTAL CONSULTANTS',
            // 'ESTATE AGENTS',
            // 'EXHIBITIONS',
            // 'EXPORT AGENTS',
            // 'EXPORTERS',
            // 'FABRICATION',
            // 'FARMING',
            // 'FASHION',
            // 'FENCING',
            // 'FILM PRODUCTION',
            // 'FINANCE',
            // 'FINANCIAL ADVISERS',
            // 'FINANCIAL SERVICES',
            // 'FIRE ALARMS',
            // 'FISH MERCHANTS',
            // 'FISHMONGERS',
            // 'FITNESS CENTRES',
            // 'FLORISTS',
            // 'FOODS',
            // 'FOOTWEAR',
            // 'FORWARDING AGENTS',
            // 'FOUNDRIES',
            // 'FREIGHT FORWARDING',
            // 'FRENCH POLISHERS',
            // 'FRUIT MERCHANTS',
            // 'FRUITERERS',
            // 'FUNERAL DIRECTORS',
            // 'FURNITURE',
            // 'GARAGES',
            // 'GARDEN CENTRES',
            // 'GARDENING',
            // 'GIFT SHOPS',
            // 'GLASS',
            // 'GLAZIERS',
            // 'GOLF CLUBS',
            // 'GRAPHIC DESIGN',
            // 'GREETING CARDS',
            // 'GROCERS',
            // 'HAIRDRESSERS',
            // 'HARDWARE',
            // 'HAULAGE',
            // 'HEALTH CARE',
            // 'HEALTH CLUBS',
            // 'HEALTH FOODS',
            // 'HEATING',
            // 'HEATING ENGINEERS',
            // 'HIRE PURCHASE',
            // 'HOLDING COMPANY',
            // 'HOLIDAYS',
            // 'HOME IMPROVEMENTS',
            // 'HORSES',
            // 'HORTICULTURE',
            // 'HOSIERY',
            // 'HOSPITALITY',
            // 'HOTELS',
            // 'HOUSE CLEARANCE',
            // 'HYDRAULIC ENGINEERS',
            // 'ICE CREAM',
            // 'IMPORT EXPORT',
            // 'IMPORTERS',
            // 'INDUSTRIAL CLEANING',
            // 'INDUSTRIAL ENGINEERS',
            // 'INFORMATION TECHNOLOGY',
            // 'INSURANCE',
            // 'INSURANCE AGENTS',
            // 'INSURANCE BROKERS',
            // 'INTERIOR DESIGN',
            // 'INVESTMENT',
            // 'INVESTMENT CONSULTANTS',
            // 'INVESTMENTS',
            // 'IRONMONGERS',
            // 'IT CONSULTANTS',
            // 'IT SERVICES',
            // 'JEWELLERS',
            // 'JOINERY',
            // 'KARTING',
            // 'KITCHENS',
            // 'KNITWEAR',
            // 'LANDSCAPE GARDENERS',
            // 'LANDSCAPING',
            // 'LAUNDRIES',
            // 'LEATHER GOODS',
            // 'LEISURE',
            // 'LETTING AGENTS',
            // 'LIGHTING',
            // 'LITHOGRAPHIC PRINTERS',
            // 'LIVESTOCK',
            // 'LOCKSMITHS',
            // 'LOGISTICS',
            // 'MACHINE TOOLS',
            // 'MACHINERY',
            // 'MANAGEMENT CONSULTANTS',
            // 'MANAGEMENT SERVICES',
            // 'MANUFACTURING',
            // 'MARINE ENGINEERS',
            // 'MARKET RESEARCH',
            // 'MARKETING',
            // 'MARKETING CONSULTANTS',
            // 'MECHANICAL ENGINEERS',
            // 'MEDIA',
            // 'MEDICAL SERVICES',
            // 'METAL MERCHANTS',
            // 'MINERAL WATER',
            // 'MOBILE PHONES',
            // 'MORTGAGE BROKERS',
            // 'MOTOR ACCESSORIES',
            // 'MOTOR CYCLES',
            // 'MOTOR ENGINEERS',
            // 'MOTOR FACTORS',
            // 'MOTOR VEHICLES',
            // 'MUSEUMS',
            // 'MUSIC',
            // 'MUSICAL INSTRUMENTS',
            // 'NEWSAGENTS',
            // 'NIGHT CLUBS',
            // 'NURSERIES',
            // 'NURSING HOMES',
            // 'OFFICE EQUIPMENT',
            // 'OFFICE SERVICES',
            // 'OFFICE SUPPLIES',
            // 'OPTICIANS',
            // 'PACKAGING',
            // 'PAINTING',
            // 'PANELLING',
            // 'PARTITIONING',
            // 'PENSION CONSULTANTS',
            // 'PERFUMERY',
            // 'PERSONNEL CONSULTANTS',
            // 'PEST CONTROL',
            // 'PET SHOPS',
            // 'PETROLEUM PRODUCTS',
            // 'PHARMACEUTICALS',
            // 'PHARMACISTS',
            // 'PHOTOCOPYING',
            // 'PHOTOGRAPHERS',
            // 'PHOTOGRAPHIC EQUIPMENT',
            // 'PHYSIOTHERAPISTS',
            // 'PICTURE FRAMING',
            // 'PLANT HIRE',
            // 'PLASTERING',
            // 'PLASTICS',
            // 'PLUMBING',
            // 'PLUMBING MERCHANTS',
            // 'POST OFFICES',
            // 'POTTERY',
            // 'PRECISION ENGINEERS',
            // 'PRINTING',
            // 'PROMOTIONS',
            // 'PROPERTY ADMINISTRATION',
            // 'PROPERTY CONSULTANTS',
            // 'PROPERTY DEVELOPMENT',
            // 'PROPERTY INVESTMENT',
            // 'PROPERTY MAINTENANCE',
            // 'PROPERTY MANAGEMENT',
            // 'PROPERTY RENTAL',
            // 'PUBLIC RELATIONS',
            // 'PUBLICANS',
            // 'PUBLISHING',
            // 'QUANTITY SURVEYORS',
            // 'QUARRYING',
            // 'RECORDS',
            // 'RECRUITMENT',
            // 'REFRIGERATION',
            // 'REMOVALS',
            // 'REPAIRS',
            // 'RESTAURANTS',
            // 'RETAIL',
            // 'ROOFING',
            // 'SADDLERY',
            // 'SAFETY EQUIPMENT',
            // 'SALVAGE',
            // 'SCAFFOLDING',
            // 'SCHOOLS',
            // 'SCRAP METAL',
            // 'SECRETARIAL SERVICES',
            // 'SECURITY',
            // 'SECURITY SERVICES',
            // 'SERVICE STATION',
            // 'SHEET METAL',
            // 'SHIPPING',
            // 'SHOPS',
            // 'SIGN MAKERS',
            // 'SIGNS',
            // 'SOCIAL CLUB',
            // 'SOFTWARE',
            // 'SOLICITORS',
            // 'SPORTS GOODS',
            // 'STATIONERS',
            // 'STEEL',
            // 'STOCKBROKERS',
            // 'STORAGE',
            // 'STRUCTURAL ENGINEERS',
            // 'SURVEYORS',
            // 'TAILORS',
            // 'TAKEAWAY',
            // 'TAXIS',
            // 'TELECOMMUNICATIONS',
            // 'TELEVISION',
            // 'TEXTILES',
            // 'TIMBER',
            // 'TIMBER MERCHANTS',
            // 'TOBACCONISTS',
            // 'TOOL HIRE',
            // 'TOOLS',
            // 'TOUR OPERATORS',
            // 'TOYS',
            // 'TRAINING',
            // 'TRANSPORT',
            // 'TRAVEL AGENTS',
            // 'TYRES',
            // 'UPHOLSTERY',
            // 'VALUERS',
            // 'VEHICLE HIRE',
            // 'VEHICLE REPAIRS',
            // 'VENTILATION',
            // 'VETERINARY SURGEONS',
            // 'VIDEO',
            // 'WAREHOUSING',
            // 'WASTE DISPOSAL',
            // 'WATCHMAKERS',
            // 'WEAVERS',
            // 'WEB DESIGN',
            // 'WHOLESALE',
            // 'WINDOW CLEANING',
            // 'WINES',
            // 'WOODWORKING',
            // 'YACHT CHARTERING'
        ];

        foreach ($objects as $name) {
            CompanyObject::updateOrCreate(['name' => $name]);
        }
    }
}
