<?php

namespace Database\Seeders;

use App\Models\SicCode;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SicCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate table to avoid duplicates if running multiple times
        DB::table('sic_codes')->truncate();

        $sicCodes = [
            ['code' => '01110', 'description' => 'Growing of cereals (except rice)'],
            ['code' => '01120', 'description' => 'Growing of rice'],
            ['code' => '01130', 'description' => 'Growing of vegetables and melons'],
            ['code' => '01140', 'description' => 'Growing of sugar cane'],
            ['code' => '01150', 'description' => 'Growing of tobacco'],
            ['code' => '01160', 'description' => 'Growing of fibre crops'],
            ['code' => '01190', 'description' => 'Growing of other non-perennial crops'],
            ['code' => '01210', 'description' => 'Growing of grapes'],
            ['code' => '01220', 'description' => 'Growing of tropical and subtropical fruits'],
            ['code' => '01230', 'description' => 'Growing of citrus fruits'],
            ['code' => '01240', 'description' => 'Growing of pome fruits and stone fruits'],
            ['code' => '01250', 'description' => 'Growing of other tree and bush fruits and nuts'],
            ['code' => '01260', 'description' => 'Growing of oleaginous fruits'],
            ['code' => '01270', 'description' => 'Growing of beverage crops'],
            ['code' => '01280', 'description' => 'Growing of spices'],
            ['code' => '01290', 'description' => 'Growing of other perennial crops'],
            ['code' => '01300', 'description' => 'Plant propagation'],
            ['code' => '01410', 'description' => 'Raising of dairy cattle'],
            ['code' => '01420', 'description' => 'Raising of other cattle and buffaloes'],
            ['code' => '01430', 'description' => 'Raising of horses and other equines'],
            ['code' => '01440', 'description' => 'Raising of camels and camelids'],
            ['code' => '01450', 'description' => 'Raising of sheep and goats'],
            ['code' => '01460', 'description' => 'Raising of swine/pigs'],
            ['code' => '01470', 'description' => 'Raising of poultry'],
            ['code' => '01490', 'description' => 'Raising of other animals'],
            ['code' => '01500', 'description' => 'Mixed farming'],
            ['code' => '01610', 'description' => 'Support activities for crop production'],
            ['code' => '01621', 'description' => 'Farm animal boarding and care'],
            ['code' => '01629', 'description' => 'Support activities for animal production n.e.c.'],
            ['code' => '01630', 'description' => 'Post-harvest crop activities'],
            ['code' => '01640', 'description' => 'Seed processing for propagation'],
            ['code' => '01700', 'description' => 'Hunting'],
            ['code' => '02100', 'description' => 'Silviculture and other forestry activities'],
            ['code' => '02200', 'description' => 'Logging'],
            ['code' => '02300', 'description' => 'Gathering of wild growing non-wood products'],
            ['code' => '02400', 'description' => 'Support services to forestry'],
            ['code' => '03110', 'description' => 'Marine fishing'],
            ['code' => '03120', 'description' => 'Freshwater fishing'],
            ['code' => '03210', 'description' => 'Marine aquaculture'],
            ['code' => '03220', 'description' => 'Freshwater aquaculture'],
            ['code' => '05101', 'description' => 'Deep coal mines'],
            ['code' => '05102', 'description' => 'Open cast coal working'],
            ['code' => '05200', 'description' => 'Mining of lignite'],
            ['code' => '06100', 'description' => 'Extraction of crude petroleum'],
            ['code' => '06200', 'description' => 'Extraction of natural gas'],
            ['code' => '07100', 'description' => 'Mining of iron ores'],
            ['code' => '07210', 'description' => 'Mining of uranium and thorium ores'],
            ['code' => '07290', 'description' => 'Mining of other non-ferrous metal ores'],
            ['code' => '08110', 'description' => 'Quarrying of ornamental and building stone'],
            ['code' => '08120', 'description' => 'Operation of gravel and sand pits'],
            ['code' => '08910', 'description' => 'Mining of chemical and fertilizer minerals'],
            ['code' => '08920', 'description' => 'Extraction of peat'],
            ['code' => '08930', 'description' => 'Extraction of salt'],
            ['code' => '08990', 'description' => 'Other mining and quarrying n.e.c.'],
            ['code' => '09100', 'description' => 'Support activities for petroleum and natural gas extraction'],
            ['code' => '09900', 'description' => 'Support activities for other mining and quarrying'],
            ['code' => '10110', 'description' => 'Processing and preserving of meat'],
            ['code' => '10120', 'description' => 'Processing and preserving of poultry meat'],
            ['code' => '10130', 'description' => 'Production of meat and poultry meat products'],
            ['code' => '10200', 'description' => 'Processing and preserving of fish'],
            ['code' => '10310', 'description' => 'Processing and preserving of potatoes'],
            ['code' => '10320', 'description' => 'Manufacture of fruit and vegetable juice'],
            ['code' => '10390', 'description' => 'Other processing and preserving of fruit and vegetables'],
            ['code' => '10410', 'description' => 'Manufacture of oils and fats'],
            ['code' => '10420', 'description' => 'Manufacture of margarine and similar edible fats'],
            ['code' => '10511', 'description' => 'Liquid milk and cream production'],
            ['code' => '10512', 'description' => 'Butter and cheese production'],
            ['code' => '10519', 'description' => 'Manufacture of other milk products'],
            ['code' => '10520', 'description' => 'Manufacture of ice cream'],
            ['code' => '10611', 'description' => 'Grain milling'],
            ['code' => '10612', 'description' => 'Manufacture of breakfast cereals'],
            ['code' => '10620', 'description' => 'Manufacture of starches and starch products'],
            ['code' => '10710', 'description' => 'Manufacture of bread; fresh pastry goods and cakes'],
            ['code' => '10720', 'description' => 'Manufacture of rusks and biscuits'],
            ['code' => '10730', 'description' => 'Manufacture of macaroni'],
            ['code' => '10810', 'description' => 'Manufacture of sugar'],
            ['code' => '10821', 'description' => 'Manufacture of cocoa and chocolate confectionery'],
            ['code' => '10822', 'description' => 'Manufacture of sugar confectionery'],
            ['code' => '10831', 'description' => 'Tea processing'],
            ['code' => '10832', 'description' => 'Production of coffee and coffee substitutes'],
            ['code' => '10840', 'description' => 'Manufacture of condiments and seasonings'],
            ['code' => '10850', 'description' => 'Manufacture of prepared meals and dishes'],
            ['code' => '10860', 'description' => 'Manufacture of homogenized food and dietetic food'],
            ['code' => '10890', 'description' => 'Manufacture of other food products n.e.c.'],
            ['code' => '10910', 'description' => 'Manufacture of prepared feeds for farm animals'],
            ['code' => '10920', 'description' => 'Manufacture of prepared pet foods'],
            ['code' => '11010', 'description' => 'Distilling'],
            ['code' => '11020', 'description' => 'Manufacture of wine from grape'],
            ['code' => '11030', 'description' => 'Manufacture of cider and other fruit wines'],
            ['code' => '11040', 'description' => 'Manufacture of other non-distilled fermented beverages'],
            ['code' => '11050', 'description' => 'Manufacture of beer'],
            ['code' => '11060', 'description' => 'Manufacture of malt'],
            ['code' => '11070', 'description' => 'Manufacture of soft drinks; mineral waters'],
            ['code' => '12000', 'description' => 'Manufacture of tobacco products'],
            ['code' => '13100', 'description' => 'Preparation and spinning of textile fibres'],
            ['code' => '13200', 'description' => 'Weaving of textiles'],
            ['code' => '13300', 'description' => 'Finishing of textiles'],
            ['code' => '13910', 'description' => 'Manufacture of knitted and crocheted fabrics'],
            ['code' => '13921', 'description' => 'Manufacture of soft furnishings'],
            ['code' => '13922', 'description' => 'Manufacture of canvas goods'],
            ['code' => '13923', 'description' => 'Manufacture of household textiles'],
            ['code' => '13931', 'description' => 'Manufacture of woven or tufted carpets and rugs'],
            ['code' => '13939', 'description' => 'Manufacture of other carpets and rugs'],
            ['code' => '13940', 'description' => 'Manufacture of cordage'],
            ['code' => '13950', 'description' => 'Manufacture of non-wovens and articles'],
            ['code' => '13960', 'description' => 'Manufacture of other technical and industrial textiles'],
            ['code' => '13990', 'description' => 'Manufacture of other textiles n.e.c.'],
            ['code' => '14110', 'description' => 'Manufacture of leather clothes'],
            ['code' => '14120', 'description' => 'Manufacture of workwear'],
            ['code' => '14131', 'description' => 'Manufacture of other men\'s outerwear'],
            ['code' => '14132', 'description' => 'Manufacture of other women\'s outerwear'],
            ['code' => '14141', 'description' => 'Manufacture of men\'s underwear'],
            ['code' => '14142', 'description' => 'Manufacture of women\'s underwear'],
            ['code' => '14190', 'description' => 'Manufacture of other wearing apparel and accessories'],
            ['code' => '14200', 'description' => 'Manufacture of articles of fur'],
            ['code' => '14310', 'description' => 'Manufacture of knitted and crocheted hosiery'],
            ['code' => '14390', 'description' => 'Manufacture of other knitted and crocheted apparel'],
            ['code' => '15110', 'description' => 'Tanning and dressing of leather'],
            ['code' => '15120', 'description' => 'Manufacture of luggage'],
            ['code' => '15200', 'description' => 'Manufacture of footwear'],
            ['code' => '16100', 'description' => 'Sawmilling and planing of wood'],
            ['code' => '16210', 'description' => 'Manufacture of veneer sheets and wood-based panels'],
            ['code' => '16220', 'description' => 'Manufacture of assembled parquet floors'],
            ['code' => '16230', 'description' => 'Manufacture of other builders\' carpentry and joinery'],
            ['code' => '16240', 'description' => 'Manufacture of wooden containers'],
            ['code' => '16290', 'description' => 'Manufacture of other products of wood or cork'],
            ['code' => '17110', 'description' => 'Manufacture of pulp'],
            ['code' => '17120', 'description' => 'Manufacture of paper and paperboard'],
            ['code' => '17211', 'description' => 'Manufacture of corrugated paper and paperboard'],
            ['code' => '17219', 'description' => 'Manufacture of other paper and paperboard containers'],
            ['code' => '17220', 'description' => 'Manufacture of household and sanitary goods'],
            ['code' => '17230', 'description' => 'Manufacture of paper stationery'],
            ['code' => '17240', 'description' => 'Manufacture of wallpaper'],
            ['code' => '17290', 'description' => 'Manufacture of other articles of paper n.e.c.'],
            ['code' => '18110', 'description' => 'Printing of newspapers'],
            ['code' => '18121', 'description' => 'Manufacture of printed labels'],
            ['code' => '18129', 'description' => 'Printing n.e.c.'],
            ['code' => '18130', 'description' => 'Pre-press and pre-media services'],
            ['code' => '18140', 'description' => 'Binding and related services'],
            ['code' => '18201', 'description' => 'Reproduction of sound recording'],
            ['code' => '18202', 'description' => 'Reproduction of video recording'],
            ['code' => '18203', 'description' => 'Reproduction of computer media'],
            ['code' => '19100', 'description' => 'Manufacture of coke oven products'],
            ['code' => '19201', 'description' => 'Mineral oil refining'],
            ['code' => '19209', 'description' => 'Other treatment of petroleum products'],
            ['code' => '20110', 'description' => 'Manufacture of industrial gases'],
            ['code' => '20120', 'description' => 'Manufacture of dyes and pigments'],
            ['code' => '20130', 'description' => 'Manufacture of other inorganic basic chemicals'],
            ['code' => '20140', 'description' => 'Manufacture of other organic basic chemicals'],
            ['code' => '20150', 'description' => 'Manufacture of fertilizers and nitrogen compounds'],
            ['code' => '20160', 'description' => 'Manufacture of plastics in primary forms'],
            ['code' => '20170', 'description' => 'Manufacture of synthetic rubber in primary forms'],
            ['code' => '20200', 'description' => 'Manufacture of pesticides and agrochemical products'],
            ['code' => '20301', 'description' => 'Manufacture of paints'],
            ['code' => '20302', 'description' => 'Manufacture of printing ink'],
            ['code' => '20411', 'description' => 'Manufacture of soap and detergents'],
            ['code' => '20412', 'description' => 'Manufacture of cleaning and polishing preparations'],
            ['code' => '20420', 'description' => 'Manufacture of perfumes and toilet preparations'],
            ['code' => '20510', 'description' => 'Manufacture of explosives'],
            ['code' => '20520', 'description' => 'Manufacture of glues'],
            ['code' => '20530', 'description' => 'Manufacture of essential oils'],
            ['code' => '20590', 'description' => 'Manufacture of other chemical products n.e.c.'],
            ['code' => '20600', 'description' => 'Manufacture of man-made fibres'],
            ['code' => '21100', 'description' => 'Manufacture of basic pharmaceutical products'],
            ['code' => '21200', 'description' => 'Manufacture of pharmaceutical preparations'],
            ['code' => '22110', 'description' => 'Manufacture of rubber tyres and tubes'],
            ['code' => '22190', 'description' => 'Manufacture of other rubber products'],
            ['code' => '22210', 'description' => 'Manufacture of plastic plates'],
            ['code' => '22220', 'description' => 'Manufacture of plastic packing goods'],
            ['code' => '22230', 'description' => 'Manufacture of builders ware of plastic'],
            ['code' => '22290', 'description' => 'Manufacture of other plastic products'],
            ['code' => '23110', 'description' => 'Manufacture of flat glass'],
            ['code' => '23120', 'description' => 'Shaping and processing of flat glass'],
            ['code' => '23130', 'description' => 'Manufacture of hollow glass'],
            ['code' => '23140', 'description' => 'Manufacture of glass fibres'],
            ['code' => '23190', 'description' => 'Manufacture and processing of other glass'],
            ['code' => '23200', 'description' => 'Manufacture of refractory products'],
            ['code' => '23310', 'description' => 'Manufacture of ceramic tiles and flags'],
            ['code' => '23320', 'description' => 'Manufacture of bricks'],
            ['code' => '23410', 'description' => 'Manufacture of ceramic household articles'],
            ['code' => '23420', 'description' => 'Manufacture of ceramic sanitary fixtures'],
            ['code' => '23430', 'description' => 'Manufacture of ceramic insulators'],
            ['code' => '23440', 'description' => 'Manufacture of other technical ceramic products'],
            ['code' => '23490', 'description' => 'Manufacture of other ceramic products n.e.c.'],
            ['code' => '23510', 'description' => 'Manufacture of cement'],
            ['code' => '23520', 'description' => 'Manufacture of lime and plaster'],
            ['code' => '23610', 'description' => 'Manufacture of concrete products for construction'],
            ['code' => '23620', 'description' => 'Manufacture of plaster products for construction'],
            ['code' => '23630', 'description' => 'Manufacture of ready-mixed concrete'],
            ['code' => '23640', 'description' => 'Manufacture of mortars'],
            ['code' => '23650', 'description' => 'Manufacture of fibre cement'],
            ['code' => '23690', 'description' => 'Manufacture of other articles of concrete'],
            ['code' => '23910', 'description' => 'Production of abrasive products'],
            ['code' => '23990', 'description' => 'Manufacture of other non-metallic mineral products'],
            ['code' => '24100', 'description' => 'Manufacture of basic iron and steel'],
            ['code' => '24200', 'description' => 'Manufacture of tubes'],
            ['code' => '24310', 'description' => 'Cold drawing of bars'],
            ['code' => '24320', 'description' => 'Cold rolling of narrow strip'],
            ['code' => '24330', 'description' => 'Cold forming or folding'],
            ['code' => '24340', 'description' => 'Cold drawing of wire'],
            ['code' => '24410', 'description' => 'Precious metals production'],
            ['code' => '24420', 'description' => 'Aluminium production'],
            ['code' => '24440', 'description' => 'Copper production'],
            ['code' => '24450', 'description' => 'Other non-ferrous metal production'],
            ['code' => '24460', 'description' => 'Processing of nuclear fuel'],
            ['code' => '24510', 'description' => 'Casting of iron'],
            ['code' => '24520', 'description' => 'Casting of steel'],
            ['code' => '24530', 'description' => 'Casting of light metals'],
            ['code' => '24540', 'description' => 'Casting of other non-ferrous metals'],
            ['code' => '25110', 'description' => 'Manufacture of metal structures'],
            ['code' => '25120', 'description' => 'Manufacture of doors and windows of metal'],
            ['code' => '25210', 'description' => 'Manufacture of central heating radiators'],
            ['code' => '25290', 'description' => 'Manufacture of other tanks'],
            ['code' => '25300', 'description' => 'Manufacture of steam generators'],
            ['code' => '25400', 'description' => 'Manufacture of weapons and ammunition'],
            ['code' => '25610', 'description' => 'Treatment and coating of metals'],
            ['code' => '25620', 'description' => 'Machining'],
            ['code' => '25710', 'description' => 'Manufacture of cutlery'],
            ['code' => '25720', 'description' => 'Manufacture of locks and hinges'],
            ['code' => '25730', 'description' => 'Manufacture of tools'],
            ['code' => '25910', 'description' => 'Manufacture of steel drums'],
            ['code' => '25920', 'description' => 'Manufacture of light metal packaging'],
            ['code' => '25930', 'description' => 'Manufacture of wire products'],
            ['code' => '25940', 'description' => 'Manufacture of fasteners and screw products'],
            ['code' => '25990', 'description' => 'Manufacture of other fabricated metal products'],
            ['code' => '26110', 'description' => 'Manufacture of electronic components'],
            ['code' => '26120', 'description' => 'Manufacture of loaded electronic boards'],
            ['code' => '26200', 'description' => 'Manufacture of computers'],
            ['code' => '26301', 'description' => 'Manufacture of telegraph and telephone apparatus'],
            ['code' => '26309', 'description' => 'Manufacture of communication equipment'],
            ['code' => '26400', 'description' => 'Manufacture of consumer electronics'],
            ['code' => '26511', 'description' => 'Manufacture of electronic measuring instruments'],
            ['code' => '26512', 'description' => 'Manufacture of industrial process control equipment'],
            ['code' => '26520', 'description' => 'Manufacture of watches and clocks'],
            ['code' => '26701', 'description' => 'Manufacture of optical precision instruments'],
            ['code' => '26702', 'description' => 'Manufacture of photographic equipment'],
            ['code' => '26800', 'description' => 'Manufacture of magnetic and optical media'],
            ['code' => '27110', 'description' => 'Manufacture of electric motors'],
            ['code' => '27120', 'description' => 'Manufacture of electricity distribution apparatus'],
            ['code' => '27200', 'description' => 'Manufacture of batteries and accumulators'],
            ['code' => '27310', 'description' => 'Manufacture of fibre optic cables'],
            ['code' => '27320', 'description' => 'Manufacture of electronic electric wires and cables'],
            ['code' => '27330', 'description' => 'Manufacture of wiring devices'],
            ['code' => '27400', 'description' => 'Manufacture of electric lighting equipment'],
            ['code' => '27510', 'description' => 'Manufacture of electric domestic appliances'],
            ['code' => '27520', 'description' => 'Manufacture of non-electric domestic appliances'],
            ['code' => '27900', 'description' => 'Manufacture of other electrical equipment'],
            ['code' => '28110', 'description' => 'Manufacture of engines and turbines'],
            ['code' => '28120', 'description' => 'Manufacture of fluid power equipment'],
            ['code' => '28131', 'description' => 'Manufacture of pumps'],
            ['code' => '28132', 'description' => 'Manufacture of compressors'],
            ['code' => '28140', 'description' => 'Manufacture of taps and valves'],
            ['code' => '28150', 'description' => 'Manufacture of bearings'],
            ['code' => '28210', 'description' => 'Manufacture of ovens'],
            ['code' => '28220', 'description' => 'Manufacture of lifting and handling equipment'],
            ['code' => '28230', 'description' => 'Manufacture of office machinery'],
            ['code' => '28240', 'description' => 'Manufacture of power-driven hand tools'],
            ['code' => '28250', 'description' => 'Manufacture of non-domestic cooling equipment'],
            ['code' => '28290', 'description' => 'Manufacture of other general-purpose machinery'],
            ['code' => '28301', 'description' => 'Manufacture of agricultural tractors'],
            ['code' => '28302', 'description' => 'Manufacture of agricultural and forestry machinery'],
            ['code' => '28410', 'description' => 'Manufacture of metal forming machinery'],
            ['code' => '28490', 'description' => 'Manufacture of other machine tools'],
            ['code' => '28910', 'description' => 'Manufacture of machinery for metallurgy'],
            ['code' => '28921', 'description' => 'Manufacture of machinery for mining'],
            ['code' => '28922', 'description' => 'Manufacture of earthmoving equipment'],
            ['code' => '28930', 'description' => 'Manufacture of machinery for food'],
            ['code' => '28940', 'description' => 'Manufacture of machinery for textile'],
            ['code' => '28950', 'description' => 'Manufacture of machinery for paperboard production'],
            ['code' => '28960', 'description' => 'Manufacture of plastics and rubber machinery'],
            ['code' => '28990', 'description' => 'Manufacture of other special-purpose machinery'],
            ['code' => '29100', 'description' => 'Manufacture of motor vehicles'],
            ['code' => '29201', 'description' => 'Manufacture of bodies for motor vehicles'],
            ['code' => '29202', 'description' => 'Manufacture of trailers and semi-trailers'],
            ['code' => '29203', 'description' => 'Manufacture of caravans'],
            ['code' => '29310', 'description' => 'Manufacture of electrical equipment for vehicles'],
            ['code' => '29320', 'description' => 'Manufacture of other parts for motor vehicles'],
            ['code' => '30110', 'description' => 'Building of ships and floating structures'],
            ['code' => '30120', 'description' => 'Building of pleasure and sporting boats'],
            ['code' => '30200', 'description' => 'Manufacture of railway locomotives'],
            ['code' => '30300', 'description' => 'Manufacture of air and spacecraft'],
            ['code' => '30400', 'description' => 'Manufacture of military fighting vehicles'],
            ['code' => '30910', 'description' => 'Manufacture of motorcycles'],
            ['code' => '30920', 'description' => 'Manufacture of bicycles and invalid carriages'],
            ['code' => '31010', 'description' => 'Manufacture of office and shop furniture'],
            ['code' => '31020', 'description' => 'Manufacture of kitchen furniture'],
            ['code' => '31030', 'description' => 'Manufacture of mattresses'],
            ['code' => '31090', 'description' => 'Manufacture of other furniture'],
            ['code' => '32110', 'description' => 'Striking of coins'],
            ['code' => '32120', 'description' => 'Manufacture of jewellery and related articles'],
            ['code' => '32200', 'description' => 'Manufacture of musical instruments'],
            ['code' => '32300', 'description' => 'Manufacture of sports goods'],
            ['code' => '32401', 'description' => 'Manufacture of professional arcade games'],
            ['code' => '32409', 'description' => 'Manufacture of other games and toys'],
            ['code' => '32500', 'description' => 'Manufacture of medical and dental instruments'],
            ['code' => '32910', 'description' => 'Manufacture of brooms and brushes'],
            ['code' => '33110', 'description' => 'Repair of fabricated metal products'],
            ['code' => '33120', 'description' => 'Repair of machinery'],
            ['code' => '33130', 'description' => 'Repair of electronic and optical equipment'],
            ['code' => '33140', 'description' => 'Repair of electrical equipment'],
            ['code' => '33150', 'description' => 'Repair and maintenance of ships and boats'],
            ['code' => '33160', 'description' => 'Repair and maintenance of aircraft'],
            ['code' => '33200', 'description' => 'Installation of industrial machinery'],
            ['code' => '35110', 'description' => 'Production of electricity'],
            ['code' => '35120', 'description' => 'Transmission of electricity'],
            ['code' => '35140', 'description' => 'Trade of electricity'],
            ['code' => '35210', 'description' => 'Manufacture of gas'],
            ['code' => '35300', 'description' => 'Steam and air conditioning supply'],
            ['code' => '36000', 'description' => 'Water collection'],
            ['code' => '37000', 'description' => 'Sewerage'],
            ['code' => '38110', 'description' => 'Collection of non-hazardous waste'],
            ['code' => '38120', 'description' => 'Collection of hazardous waste'],
            ['code' => '38210', 'description' => 'Treatment and disposal of non-hazardous waste'],
            ['code' => '38320', 'description' => 'Recovery of sorted materials'],
            ['code' => '41100', 'description' => 'Development of building projects'],
            ['code' => '41201', 'description' => 'Construction of commercial buildings'],
            ['code' => '41202', 'description' => 'Construction of domestic buildings'],
            ['code' => '42110', 'description' => 'Construction of roads and motorways'],
            ['code' => '42130', 'description' => 'Construction of bridges and tunnels'],
            ['code' => '42210', 'description' => 'Construction of utility projects for fluids'],
            ['code' => '43110', 'description' => 'Demolition'],
            ['code' => '43210', 'description' => 'Electrical installation'],
            ['code' => '43220', 'description' => 'Plumbing'],
            ['code' => '43310', 'description' => 'Plastering'],
            ['code' => '43320', 'description' => 'Joinery installation'],
            ['code' => '43341', 'description' => 'Painting'],
            ['code' => '43910', 'description' => 'Roofing activities'],
            ['code' => '45111', 'description' => 'Sale of new cars and light motor vehicles'],
            ['code' => '45112', 'description' => 'Sale of used cars and light motor vehicles'],
            ['code' => '45200', 'description' => 'Maintenance and repair of motor vehicles'],
            ['code' => '46110', 'description' => 'Agents selling agricultural raw materials'],
            ['code' => '46190', 'description' => 'Agents involved in the sale of a variety of goods'],
            ['code' => '46310', 'description' => 'Wholesale of fruit and vegetables'],
            ['code' => '46342', 'description' => 'Wholesale of wine'],
            ['code' => '46420', 'description' => 'Wholesale of clothing and footwear'],
            ['code' => '46510', 'description' => 'Wholesale of computers'],
            ['code' => '46730', 'description' => 'Wholesale of wood'],
            ['code' => '47110', 'description' => 'Retail sale in non-specialised stores with food'],
            ['code' => '47190', 'description' => 'Other retail sale in non-specialised stores'],
            ['code' => '47410', 'description' => 'Retail sale of computers'],
            ['code' => '47599', 'description' => 'Retail of furniture'],
            ['code' => '47710', 'description' => 'Retail sale of clothing in specialised stores'],
            ['code' => '47910', 'description' => 'Retail sale via mail order houses or via Internet'],
            ['code' => '49100', 'description' => 'Passenger rail transport'],
            ['code' => '49311', 'description' => 'Urban and suburban passenger railway underground'],
            ['code' => '49319', 'description' => 'Other urban'],
            ['code' => '49320', 'description' => 'Taxi operation'],
            ['code' => '49390', 'description' => 'Other passenger land transport'],
            ['code' => '49410', 'description' => 'Freight transport by road'],
            ['code' => '49420', 'description' => 'Removal services'],
            ['code' => '49500', 'description' => 'Transport via pipeline'],
            ['code' => '50100', 'description' => 'Sea and coastal passenger water transport'],
            ['code' => '50200', 'description' => 'Sea and coastal freight water transport'],
            ['code' => '50300', 'description' => 'Inland passenger water transport'],
            ['code' => '50400', 'description' => 'Inland freight water transport'],
            ['code' => '51101', 'description' => 'Scheduled passenger air transport'],
            ['code' => '51102', 'description' => 'Non-scheduled passenger air transport'],
            ['code' => '51210', 'description' => 'Freight air transport'],
            ['code' => '51220', 'description' => 'Space transport'],
            ['code' => '52101', 'description' => 'Operation of warehousing and storage facilities for water transport activities'],
            ['code' => '52102', 'description' => 'Operation of warehousing and storage facilities for air transport activities'],
            ['code' => '52103', 'description' => 'Operation of warehousing and storage facilities for land transport activities'],
            ['code' => '52211', 'description' => 'Operation of rail freight terminals'],
            ['code' => '52212', 'description' => 'Operation of rail passenger facilities at railway stations'],
            ['code' => '52213', 'description' => 'Operation of bus and coach passenger facilities at bus and coach stations'],
            ['code' => '52219', 'description' => 'Other service activities incidental to land transportation'],
            ['code' => '52220', 'description' => 'Service activities incidental to water transportation'],
            ['code' => '52230', 'description' => 'Service activities incidental to air transportation'],
            ['code' => '52241', 'description' => 'Cargo handling for water transport activities'],
            ['code' => '52242', 'description' => 'Cargo handling for air transport activities'],
            ['code' => '52243', 'description' => 'Cargo handling for land transport activities'],
            ['code' => '52290', 'description' => 'Other transportation support activities'],
            ['code' => '53100', 'description' => 'Postal activities under universal service obligation'],
            ['code' => '53201', 'description' => 'Licensed carriers'],
            ['code' => '53202', 'description' => 'Unlicensed carrier'],
            ['code' => '55100', 'description' => 'Hotels and similar accommodation'],
            ['code' => '55201', 'description' => 'Holiday centres and villages'],
            ['code' => '55202', 'description' => 'Youth hostels'],
            ['code' => '55209', 'description' => 'Other holiday and other collective accommodation'],
            ['code' => '55300', 'description' => 'Recreational vehicle parks'],
            ['code' => '55900', 'description' => 'Other accommodation'],
            ['code' => '56101', 'description' => 'Licensed restaurants'],
            ['code' => '56102', 'description' => 'Unlicensed restaurants and cafes'],
            ['code' => '56103', 'description' => 'Take-away food shops and mobile food stands'],
            ['code' => '56210', 'description' => 'Event catering activities'],
            ['code' => '56290', 'description' => 'Other food services'],
            ['code' => '56301', 'description' => 'Licensed clubs'],
            ['code' => '56302', 'description' => 'Public houses and bars'],
            ['code' => '58110', 'description' => 'Book publishing'],
            ['code' => '58120', 'description' => 'Publishing of directories and mailing lists'],
            ['code' => '58130', 'description' => 'Publishing of newspapers'],
            ['code' => '58141', 'description' => 'Publishing of learned journals'],
            ['code' => '58142', 'description' => 'Publishing of consumer and business journals and periodicals'],
            ['code' => '58190', 'description' => 'Other publishing activities'],
            ['code' => '58210', 'description' => 'Publishing of computer games'],
            ['code' => '58290', 'description' => 'Other software publishing'],
            ['code' => '59111', 'description' => 'Motion picture production activities'],
            ['code' => '59112', 'description' => 'Video production activities'],
            ['code' => '59113', 'description' => 'Television programme production activities'],
            ['code' => '59120', 'description' => 'Motion picture activities'],
            ['code' => '59131', 'description' => 'Motion picture distribution activities'],
            ['code' => '59132', 'description' => 'Video distribution activities'],
            ['code' => '59133', 'description' => 'Television programme distribution activities'],
            ['code' => '59140', 'description' => 'Motion picture projection activities'],
            ['code' => '59200', 'description' => 'Sound recording and music publishing activities'],
            ['code' => '60100', 'description' => 'Radio broadcasting'],
            ['code' => '60200', 'description' => 'Television programming and broadcasting activities'],

        ];

        // Using chunk to handle large datasets efficiently
        foreach (array_chunk($sicCodes, 100) as $chunk) {
            SicCode::insert($chunk);
        }
    }
}
